name: Markdown Checker

on:
  pull_request:
    paths:
      - '**.md'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pokreni Markdown linter
        uses: avto-dev/markdown-lint@v1
